## Pandas - Importing data

Please download from Google Drive <a href="https://drive.google.com/file/d/1lN5Eh2wz_DDOlcI7as9gQcmUALNqs0_y/view?usp=share_link">this data</a>.

In [23]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

- ```ems_2019_first_6_months.csv``` into a dataframe named ```ems_19_first_df```

In [26]:
## import data and store in dataframe
ems_19_first_df = pd.read_csv ("wk4-hw-data/ems_2019_first_6_months.csv")
ems_19_first_df

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,190010111,2019-01-01 00:24:51,SICK,6,SICK,6,01/01/2019 12:25:28 AM,Y,37,01/01/2019 12:25:56 AM,...,9.0,2.0,103.0,1.0,12.0,N,N,N,N,chunk10.csv
1,190010112,2019-01-01 00:25:22,DRUG,4,DRUG,4,01/01/2019 12:25:39 AM,Y,17,01/01/2019 12:26:03 AM,...,23.0,9.0,111.0,4.0,13.0,N,N,N,N,chunk10.csv
2,190010113,2019-01-01 00:25:52,DRUG,4,DRUG,4,01/01/2019 12:25:57 AM,Y,5,01/01/2019 12:26:11 AM,...,63.0,45.0,318.0,22.0,8.0,N,N,N,N,chunk13.csv
3,190010114,2019-01-01 00:25:52,OBMAJ,3,OBMAJ,3,01/01/2019 12:26:13 AM,Y,21,01/01/2019 12:26:24 AM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk14.csv
4,190010115,2019-01-01 00:26:03,EDP,7,EDP,7,01/01/2019 12:26:12 AM,Y,9,01/01/2019 12:26:29 AM,...,101.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk14.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754651,190010106,2019-01-01 00:24:12,DRUG,4,DRUG,4,01/01/2019 12:28:52 AM,Y,280,01/01/2019 12:28:52 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754652,190010107,2019-01-01 00:24:14,UNC,2,UNC,2,01/01/2019 12:24:38 AM,Y,24,01/01/2019 12:24:57 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754653,190010108,2019-01-01 00:24:16,INJMAJ,3,INJMAJ,3,01/01/2019 12:25:50 AM,Y,94,01/01/2019 12:25:50 AM,...,18.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754654,190010109,2019-01-01 00:24:23,CARD,3,CARD,3,01/01/2019 12:25:08 AM,Y,45,01/01/2019 12:25:27 AM,...,50.0,14.0,208.0,10.0,13.0,N,N,N,N,chunk82.csv
754655,190010110,2019-01-01 00:24:35,DRUG,4,DRUG,4,01/01/2019 12:25:28 AM,Y,53,01/01/2019 12:25:40 AM,...,62.0,47.0,311.0,20.0,10.0,N,N,N,N,chunk82.csv

In [28]:
## call the first 10 rows
ems_19_first_df.head (10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,190010111,2019-01-01 00:24:51,SICK,6,SICK,6,01/01/2019 12:25:28 AM,Y,37,01/01/2019 12:25:56 AM,...,9.0,2.0,103.0,1.0,12.0,N,N,N,N,chunk10.csv
1,190010112,2019-01-01 00:25:22,DRUG,4,DRUG,4,01/01/2019 12:25:39 AM,Y,17,01/01/2019 12:26:03 AM,...,23.0,9.0,111.0,4.0,13.0,N,N,N,N,chunk10.csv
2,190010113,2019-01-01 00:25:52,DRUG,4,DRUG,4,01/01/2019 12:25:57 AM,Y,5,01/01/2019 12:26:11 AM,...,63.0,45.0,318.0,22.0,8.0,N,N,N,N,chunk13.csv
3,190010114,2019-01-01 00:25:52,OBMAJ,3,OBMAJ,3,01/01/2019 12:26:13 AM,Y,21,01/01/2019 12:26:24 AM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk14.csv
4,190010115,2019-01-01 00:26:03,EDP,7,EDP,7,01/01/2019 12:26:12 AM,Y,9,01/01/2019 12:26:29 AM,...,101.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk14.csv
5,190073272,2019-01-07 17:49:43,EDP,7,EDP,7,01/07/2019 05:49:50 PM,Y,7,01/07/2019 05:50:04 PM,...,17.0,5.0,106.0,2.0,12.0,N,N,N,N,chunk149.csv
6,190073416,2019-01-07 18:27:54,EDP,7,EDP,7,01/07/2019 06:28:33 PM,Y,39,01/07/2019 06:28:44 PM,...,6.0,3.0,102.0,2.0,10.0,N,N,N,N,chunk149.csv
7,190081434,2019-01-08 10:28:31,UNKNOW,4,UNKNOW,4,01/08/2019 10:29:19 AM,Y,48,01/08/2019 10:29:36 AM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk149.csv
8,190081743,2019-01-08 11:43:35,UNKNOW,4,UNKNOW,4,01/08/2019 11:43:47 AM,Y,12,01/08/2019 11:43:55 AM,...,7.0,1.0,103.0,2.0,12.0,N,N,N,N,chunk149.csv
9,190081744,2019-01-08 11:43:48,EDP,7,EDP,7,01/08/2019 11:43:59 AM,Y,11,01/08/2019 11:44:30 AM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk149.csv

In [30]:
## call the last 5 rows
ems_19_first_df.tail ()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
754651,190010106,2019-01-01 00:24:12,DRUG,4,DRUG,4,01/01/2019 12:28:52 AM,Y,280,01/01/2019 12:28:52 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754652,190010107,2019-01-01 00:24:14,UNC,2,UNC,2,01/01/2019 12:24:38 AM,Y,24,01/01/2019 12:24:57 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754653,190010108,2019-01-01 00:24:16,INJMAJ,3,INJMAJ,3,01/01/2019 12:25:50 AM,Y,94,01/01/2019 12:25:50 AM,...,18.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754654,190010109,2019-01-01 00:24:23,CARD,3,CARD,3,01/01/2019 12:25:08 AM,Y,45,01/01/2019 12:25:27 AM,...,50.0,14.0,208.0,10.0,13.0,N,N,N,N,chunk82.csv
754655,190010110,2019-01-01 00:24:35,DRUG,4,DRUG,4,01/01/2019 12:25:28 AM,Y,53,01/01/2019 12:25:40 AM,...,62.0,47.0,311.0,20.0,10.0,N,N,N,N,chunk82.csv

In [31]:
## call a 20 random rows
ems_19_first_df.sample (20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
343063,190882191,2019-03-29 13:10:43,DRUG,4,DRUG,4,03/29/2019 01:31:30 PM,Y,1247,03/29/2019 01:31:55 PM,...,44.0,17.0,204.0,9.0,15.0,N,N,N,N,chunk153.csv
407558,191034143,2019-04-13 21:43:10,UNKNOW,4,UNKNOW,4,04/13/2019 09:43:20 PM,Y,10,04/13/2019 09:43:32 PM,...,73.0,41.0,316.0,23.0,9.0,N,N,N,N,chunk153.csv
267226,190700429,2019-03-11 03:29:05,SICMIN,7,SICMIN,7,03/11/2019 03:29:35 AM,Y,30,03/11/2019 03:29:52 AM,...,113.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk152.csv
9545,190051200,2019-01-05 08:15:32,UNC,2,UNC,2,01/05/2019 08:15:48 AM,Y,16,01/05/2019 08:16:47 AM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk149.csv
525892,191322404,2019-05-12 15:37:00,UNKNOW,4,UNKNOW,4,05/12/2019 03:37:14 PM,Y,14,05/12/2019 03:37:30 PM,...,60.0,47.0,313.0,21.0,8.0,N,N,N,N,chunk155.csv
380147,190971881,2019-04-07 12:26:37,UNC,2,UNC,2,04/07/2019 12:27:11 PM,Y,34,04/07/2019 12:27:37 PM,...,30.0,7.0,109.0,6.0,13.0,N,N,N,N,chunk153.csv
164704,190440418,2019-02-13 04:05:17,RESPIR,4,RESPIR,4,02/13/2019 04:05:28 AM,Y,11,02/13/2019 04:05:40 AM,...,50.0,11.0,208.0,10.0,16.0,N,N,N,N,chunk151.csv
353525,190910261,2019-04-01 02:14:11,SICK,6,SICK,6,04/01/2019 02:14:37 AM,Y,26,04/01/2019 02:14:45 AM,...,107.0,24.0,408.0,28.0,6.0,N,N,N,N,chunk153.csv
621624,191542590,2019-06-03 14:49:52,EDP,7,EDPC,7,06/03/2019 02:50:09 PM,Y,17,06/03/2019 02:50:26 PM,...,109.0,20.0,407.0,25.0,6.0,N,N,N,N,chunk156.csv
382455,190980129,2019-04-08 00:49:55,ABDPN,5,ABDPN,5,04/08/2019 12:50:18 AM,Y,23,04/08/2019 12:50:31 AM,...,83.0,37.0,304.0,32.0,7.0,N,N,N,N,chunk153.csv
498966,191261712,2019-05-06 11:11:28,CARDBR,2,CARDBR,2,05/06/2019 11:12:07 AM,Y,39,05/06/2019 11:12:39 AM,...,110.0,21.0,404.0,24.0,14.0,N,N,N,N,chunk154.csv
460993,191164301,2019-04-26 23:51:18,UNKNOW,4,UNKNOW,4,04/26/2019 11:51:51 PM,Y,33,04/26/2019 11:52:05 PM,...,42.0,17.0,203.0,12.0,15.0,N,N,N,N,chunk154.csv
12596,190061647,2019-01-06 11:52:27,ANAPH,2,ANAPH,2,01/06/2019 11:52:51 AM,Y,24,01/06/2019 11:52:59 AM,...,14.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk149.csv
352901,190903752,2019-03-31 21:42:04,UNC,2,UNC,2,03/31/2019 09:42:24 PM,Y,20,03/31/2019 09:42:49 PM,...,25.0,9.0,111.0,5.0,13.0,N,N,N,N,chunk153.csv
210297,190552987,2019-02-24 18:55:51,EDPC,5,EDPC,5,02/24/2019 06:56:00 PM,Y,9,02/24/2019 06:56:10 PM,...,1.0,1.0,101.0,2.0,10.0,N,N,N,N,chunk151.csv
123416,190340568,2019-02-03 03:25:16,SICMIN,7,SICMIN,7,02/03/2019 03:25:34 AM,Y,18,02/03/2019 03:25:42 AM,...,88.0,35.0,302.0,13.0,8.0,N,N,N,N,chunk151.csv
605757,191504575,2019-05-30 23:44:08,UNKNOW,4,UNKNOW,4,05/30/2019 11:45:21 PM,Y,73,05/30/2019 11:47:17 PM,...,13.0,2.0,106.0,2.0,12.0,N,N,N,N,chunk155.csv
530966,191334056,2019-05-13 21:13:00,SICK,6,INHALE,5,05/13/2019 09:13:30 PM,Y,30,05/13/2019 09:13:47 PM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk155.csv
662618,191633935,2019-06-12 20:05:34,CVA,4,CVA,4,06/12/2019 08:05:57 PM,Y,23,06/12/2019 08:06:09 PM,...,120.0,49.0,501.0,31.0,11.0,N,N,N,N,chunk156.csv
415512,191053776,2019-04-15 18:55:02,UNC,2,UNC,2,04/15/2019 06:55:12 PM,Y,10,04/15/2019 06:55:29 PM,...,44.0,16.0,204.0,7.0,15.0,N,N,N,N,chunk154.csv

In [56]:
## get basic overview of the data
ems_19_first_df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754656 entries, 0 to 754655
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   CAD_INCIDENT_ID                 754656 non-null  int64
 1   INCIDENT_DATETIME               754656 non-null  object
 2   INITIAL_CALL_TYPE               754656 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     754656 non-null  int64
 4   FINAL_CALL_TYPE                 754656 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       754656 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       749544 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  754656 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    754656 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       748561 non-null  object
 10  FIRST_ON_SCENE_DATETIME         729221 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  754656 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    729068 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   729221 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          522462 non-null  object
 15  FIRST_HOSP_ARRIVAL_DATETIME     518867 non-null  object
 16  INCIDENT_CLOSE_DATETIME         754540 non-null  object
 17  HELD_INDICATOR                  754656 non-null  object
 18  INCIDENT_DISPOSITION_CODE       748265 non-null  float64
 19  BOROUGH                         754656 non-null  object
 20  INCIDENT_DISPATCH_AREA          754656 non-null  object
 21  ZIPCODE                         745086 non-null  float64
 22  POLICEPRECINCT                  745102 non-null  float64
 23  CITYCOUNCILDISTRICT             745071 non-null  float64
 24  COMMUNITYDISTRICT               745101 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         744542 non-null  float64
 26  CONGRESSIONALDISTRICT           745071 non-null  float64
 27  REOPEN_INDICATOR                754656 non-null  object
 28  SPECIAL_EVENT_INDICATOR         754656 non-null  object
 29  STANDBY_INDICATOR               754656 non-null  object
 30  TRANSFER_INDICATOR              754656 non-null  object
 31  source                          754656 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 184.2+ MB

In [59]:
## what datatypes do the different columns hold?
type(ems_19_first_df.shape)

tuple

In [60]:
## how many rows and columns are there?
ems_19_first_df.shape

(754656, 32)

### In three separate cells, ingest the 3 other related datasets into this notebook:

- ```ems_2019_last_6_months.csv``` into a dataframe named ```ems_19_last_df```
- ```ems_2020_first_6_months.csv``` into a dataframe named ```ems_20_first_df```
- ```ems_2020_last_6_months.csv``` into a dataframe named ```ems_20_last_df```

We want to combine all 4 dataframes so we can run an analysis on the combined dataframes

In [43]:
### For last 6 months of 2019
## call the dataframe to see what you have

ems_19_last_df = pd.read_csv ("wk4-hw-data/ems_2019_last_6_months.csv")
ems_19_last_df

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,191853909,2019-07-04 21:07:53,DRUG,4,DRUG,4,07/04/2019 09:08:16 PM,Y,23,07/04/2019 09:08:26 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
1,191864927,2019-07-05 21:09:53,MVAINJ,4,MVAINJ,4,07/05/2019 09:10:10 PM,Y,17,07/05/2019 09:10:20 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
2,191870823,2019-07-06 05:32:12,INJURY,5,INJURY,5,07/06/2019 05:32:49 AM,Y,37,07/06/2019 05:33:40 AM,...,47.0,12.0,212.0,11.0,16.0,N,N,N,N,chunk157.csv
3,191870824,2019-07-06 05:33:49,UNC,2,UNC,2,07/06/2019 05:33:57 AM,Y,8,07/06/2019 05:34:25 AM,...,32.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk157.csv
4,191870897,2019-07-06 06:20:26,INJURY,5,INJURY,5,07/06/2019 06:20:43 AM,Y,17,07/06/2019 06:20:53 AM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781735,192702998,2019-09-27 16:20:29,EDP,7,UNKNOW,4,09/27/2019 04:21:09 PM,Y,40,09/27/2019 04:21:21 PM,...,100.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk81.csv
781736,192704269,2019-09-27 21:05:14,OTHER,6,OTHER,6,09/27/2019 09:05:26 PM,Y,12,09/27/2019 09:07:15 PM,...,43.0,18.0,209.0,8.0,15.0,N,N,N,N,chunk81.csv
781737,193012678,2019-10-28 15:01:30,MVAINJ,4,MVAINJ,4,10/28/2019 03:01:30 PM,Y,0,10/28/2019 03:01:30 PM,...,109.0,20.0,407.0,25.0,6.0,N,N,N,N,chunk81.csv
781738,193330212,2019-11-29 01:16:42,EDP,7,EDP,7,11/29/2019 01:17:36 AM,Y,54,11/29/2019 01:17:53 AM,...,28.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk81.csv
781739,193634478,2019-12-29 23:59:34,EDP,7,EDP,7,NaN,N,0,NaN,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk81.csv

In [44]:
### For first 6 months of 2020
## call the dataframe to see what you have
ems_20_first_df = pd.read_csv ("wk4-hw-data/ems_2020_first_6_months.csv")
ems_20_first_df

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201012966,2020-04-10 14:36:07,SICK,6,SICK,6,04/10/2020 02:36:37 PM,Y,30,04/10/2020 02:37:36 PM,...,101.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk148.csv
1,201013858,2020-04-10 17:37:57,SICKFC,6,SICKFC,6,04/10/2020 05:56:30 PM,Y,1113,04/10/2020 05:56:30 PM,...,42.0,17.0,203.0,12.0,15.0,N,N,N,N,chunk148.csv
2,201013897,2020-04-10 17:46:07,HYPTN,7,HYPTN,7,04/10/2020 05:51:43 PM,Y,336,04/10/2020 05:51:47 PM,...,62.0,43.0,311.0,20.0,11.0,N,N,N,N,chunk148.csv
3,201014048,2020-04-10 18:19:32,SICKFC,6,SICKFC,6,04/10/2020 06:19:54 PM,Y,22,04/10/2020 06:23:23 PM,...,52.0,14.0,207.0,10.0,13.0,N,N,N,N,chunk148.csv
4,201014049,2020-04-10 18:19:33,INJURY,5,INJURY,5,04/10/2020 06:25:55 PM,Y,382,04/10/2020 06:26:14 PM,...,103.0,27.0,412.0,28.0,5.0,N,N,N,N,chunk148.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741802,201824116,2020-06-30 23:58:45,INJURY,5,INJURY,5,06/30/2020 11:58:56 PM,Y,11,06/30/2020 11:59:18 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk172.csv
741803,201824117,2020-06-30 23:59:00,DRUG,4,DRUG,4,06/30/2020 11:59:24 PM,Y,24,06/30/2020 11:59:40 PM,...,61.0,47.0,315.0,21.0,11.0,N,N,N,N,chunk172.csv
741804,201824118,2020-06-30 23:59:26,INJURY,5,INJURY,5,06/30/2020 11:59:40 PM,Y,14,06/30/2020 11:59:57 PM,...,30.0,7.0,109.0,6.0,13.0,N,N,N,N,chunk172.csv
741805,200293244,2020-01-29 17:15:18,UNKNOW,4,UNKNOW,4,01/29/2020 05:47:34 PM,Y,1936,01/29/2020 05:47:57 PM,...,14.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk81.csv
741806,200293566,2020-01-29 18:32:45,EDPC,7,EDPC,7,NaN,N,0,NaN,...,9.0,2.0,102.0,2.0,12.0,N,N,N,N,chunk81.csv

In [45]:
### For last 6 months of 2020
## call the dataframe to see what you have

ems_20_last_df = pd.read_csv ("wk4-hw-data/ems_2020_last_6_months.csv")
ems_20_last_df

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201853344,2020-07-03 19:51:35,MVAINJ,4,MVAINJ,4,07/03/2020 07:52:54 PM,Y,79,07/03/2020 07:53:13 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk172.csv
1,201861781,2020-07-04 13:38:45,INJURY,5,INJURY,5,07/04/2020 01:38:55 PM,Y,10,07/04/2020 01:39:01 PM,...,20.0,3.0,107.0,3.0,10.0,N,N,N,N,chunk172.csv
2,201862931,2020-07-04 19:06:08,INJURY,5,INJURY,5,07/04/2020 07:06:34 PM,Y,26,07/04/2020 07:06:53 PM,...,60.0,47.0,313.0,21.0,8.0,N,N,N,N,chunk172.csv
3,201870048,2020-07-05 00:09:31,SICK,6,SICK,6,NaN,N,0,NaN,...,46.0,14.0,205.0,10.0,15.0,N,N,N,N,chunk172.csv
4,201870159,2020-07-05 00:31:24,EDPC,7,SICK,6,NaN,N,0,NaN,...,43.0,17.0,209.0,12.0,15.0,N,N,N,N,chunk172.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670750,203664156,2020-12-31 23:58:15,DIFFBR,2,DIFFBR,2,12/31/2020 11:58:26 PM,Y,11,12/31/2020 11:59:10 PM,...,79.0,36.0,303.0,14.0,7.0,N,N,N,N,chunk214.csv
670751,203664157,2020-12-31 23:58:27,INJURY,5,INJURY,5,12/31/2020 11:59:57 PM,Y,90,01/01/2021 12:01:00 AM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk214.csv
670752,203664158,2020-12-31 23:58:38,CARDBR,2,CARDBR,2,12/31/2020 11:59:32 PM,Y,54,12/31/2020 11:59:40 PM,...,30.0,7.0,109.0,6.0,13.0,N,N,N,N,chunk214.csv
670753,203664159,2020-12-31 23:58:46,MVAINJ,4,MVAINJ,4,12/31/2020 11:59:37 PM,Y,51,01/01/2021 12:01:00 AM,...,48.0,17.0,206.0,12.0,15.0,N,N,N,N,chunk214.csv
670754,203664161,2020-12-31 23:59:13,CARDBR,2,CARDBR,2,01/01/2021 12:00:22 AM,Y,69,01/01/2021 12:01:10 AM,...,77.0,36.0,308.0,16.0,9.0,N,N,N,N,chunk214.csv

## Combine the 4 dataframes

In [67]:
## create a list to combine all 
list_ems_df = [{ems_19_last_df},{ems_20_first_df},{ems_20_last_df}]

In [61]:
## combine (concat) the dfs
ems_df_delays = pd.concat ([ems_19_last_df, ems_20_first_df, ems_20_last_df])
ems_df_delays

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,191853909,2019-07-04 21:07:53,DRUG,4,DRUG,4,07/04/2019 09:08:16 PM,Y,23,07/04/2019 09:08:26 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
1,191864927,2019-07-05 21:09:53,MVAINJ,4,MVAINJ,4,07/05/2019 09:10:10 PM,Y,17,07/05/2019 09:10:20 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
2,191870823,2019-07-06 05:32:12,INJURY,5,INJURY,5,07/06/2019 05:32:49 AM,Y,37,07/06/2019 05:33:40 AM,...,47.0,12.0,212.0,11.0,16.0,N,N,N,N,chunk157.csv
3,191870824,2019-07-06 05:33:49,UNC,2,UNC,2,07/06/2019 05:33:57 AM,Y,8,07/06/2019 05:34:25 AM,...,32.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk157.csv
4,191870897,2019-07-06 06:20:26,INJURY,5,INJURY,5,07/06/2019 06:20:43 AM,Y,17,07/06/2019 06:20:53 AM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670750,203664156,2020-12-31 23:58:15,DIFFBR,2,DIFFBR,2,12/31/2020 11:58:26 PM,Y,11,12/31/2020 11:59:10 PM,...,79.0,36.0,303.0,14.0,7.0,N,N,N,N,chunk214.csv
670751,203664157,2020-12-31 23:58:27,INJURY,5,INJURY,5,12/31/2020 11:59:57 PM,Y,90,01/01/2021 12:01:00 AM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk214.csv
670752,203664158,2020-12-31 23:58:38,CARDBR,2,CARDBR,2,12/31/2020 11:59:32 PM,Y,54,12/31/2020 11:59:40 PM,...,30.0,7.0,109.0,6.0,13.0,N,N,N,N,chunk214.csv
670753,203664159,2020-12-31 23:58:46,MVAINJ,4,MVAINJ,4,12/31/2020 11:59:37 PM,Y,51,01/01/2021 12:01:00 AM,...,48.0,17.0,206.0,12.0,15.0,N,N,N,N,chunk214.csv
670754,203664161,2020-12-31 23:59:13,CARDBR,2,CARDBR,2,01/01/2021 12:00:22 AM,Y,69,01/01/2021 12:01:10 AM,...,77.0,36.0,308.0,16.0,9.0,N,N,N,N,chunk214.csv

#### Programmatically (not with a calculator) confirm that their row totals add up to the correct number

In [ ]:
## how many rows does the combined df have
ems_df_delays.shape

In [ ]:
## get total rows when you add up all the individual dataframes
ems_19_last_df.shape [0] + ems_20_first_df.shape [0] + ems_20_last_df.shape [0]

## Ingest Massive Dataset

Step 1. Open ```global_temps.csv``` in Excel first. What happened?

Step 2. Open this data set in Pandas.

In [ ]:
## import global_temps.csv into a df called temps_df
global_temps = pd.read_csv (wk4-hw-data/global_temps.csv)

global_temps

## How many rows of data does this dataset have?

In [ ]:
## How many rows?
global_temps.shape

## Targeting an Excel sheet

We need the Customs and Border Protection data in this ```multi-data.xlsx``` workbook.

Note that this is an excerpt of the actual CBP data.

In [51]:
### import it here
border_data = pd.read_excel ("wk4-hw-data/multi-data.xlsx")
border_data

,Serial Number,County,License Type Code,License Class Code,Certificate Number,Premise Name,DBA,Premise Address,Premise Address 2,Premise City,...,Premise Zip,License Issued Date,License Expiration Date,Method of Operation,Days/Hours of Operation,Other,Georeference,Zone,Effective Date,Original Date
0,2000777,ALBANY,HL,242,912771,SUPER HOST HOTELS INC,ALBANY RAMADA PLAZA,3 WATERVLIET AVE,NaN,ALBANY,...,12206,2019-11-15,2021-11-30,HOTEL RESTAURANT SERVING BEER WINE CIDER AND L...,NaN,NaN,POINT (-73.783705 42.674761),2,2019-12-01,1996-12-05
1,1197749,NASSAU,CT,246,913036,MEMORARE CATERERS INC,NaN,2183 JACKSON AVE A,WAVERLY AVE & MERRICK ROAD,SEAFORD,...,11783,2019-11-22,2021-11-30,CATERER SERVING BEER CIDER WINE AND LIQUOR,NaN,NaN,POINT (-73.487062 40.668214),1,2019-12-01,2007-12-18
2,2149537,SULLIVAN,AX,122,910149,AHMED TRADING INC,NaN,1302 STATE ROUTE 52,NaN,LOCH SHELDRAKE,...,12759,2018-11-19,2021-11-30,GROCERY SELLING BEER CIDER AND WINE PRODUCTS,NaN,NaN,POINT (-74.66699 41.777859),2,2018-12-01,2009-12-22
3,1311950,QUEENS,W,322,903719,CAOTICO LLC,FORET WINES,68-38 FOREST AVE,STOREFRONT C,RIDGEWOOD,...,11385,2018-12-31,2021-11-30,WINE STORE SELLING WINE,NaN,NaN,POINT (-73.90109 40.702673),1,2018-12-31,2018-12-31
4,2217319,PUTNAM,TW,344,917985,COFFEE TIME CAFE INC,NaN,559 RTE 6N,NaN,MAHOPAC,...,10541,2019-12-05,2021-11-30,TAVERN SERVING BEER AND WINE,NaN,NaN,POINT (-73.763883 41.374319),2,2019-12-05,2019-12-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50135,1311238,QUEENS,AX,122,847423,ZAHER MEAT CORP,REGO FRESH MARKETPLACE,63-76 WOODHAVEN BLVD,NaN,REGO PARK,...,11374,2021-07-07,2024-08-31,"GROCERY STORE SELLING BEER, WINE PRODUCTS AND ...",NaN,NaN,POINT (-73.86759 40.722457),1,2021-09-01,2018-09-12
50136,3002671,ERIE,AX,122,782775,WOODLAWN DELI INC,NaN,S 3306 LAKE SHORE ROAD,T/O WOODLAWN,BLASDELL,...,14219,2021-10-08,2024-10-31,GROCERY STORE SELLING BEER CIDER AND WINE PROD...,NaN,NaN,NaN,3,2021-11-01,1994-11-30
50137,2209433,ONONDAGA,AX,128,784064,7 ELEVEN INC,SUNOCO A PLUS #40215H,1000 W GENESEE ST,NaN,SYRACUSE,...,13204,2021-10-28,2024-10-31,GROCERY STORE SELLING BEER CIDER & WINE PRODUCTS,NaN,NaN,POINT (-76.17092 43.053662),2,2021-11-01,2018-02-01
50138,1312336,BRONX,CM,110,801200,TORCH & CROWN 704 BROADWAY LLC,TORCH & CROWN BREWING COMPANY,463 E 173RD ST,NaN,BRONX,...,10457,2021-11-08,2024-11-30,COMBINED CRAFT MANUFACTURER,Micro Brewer Serial #1312333,Farm Brewer Serial #1312335,POINT (-73.901384 40.841683),1,2021-12-01,2018-12-24
50139,2227379,ALBANY,WS,308,941478,DUSKY GOOSE LLC,DUSKY GOOSE,8355 NE WARREN RD,WWW.DUSKYGOOSE.COM,DUNDEE,...,97115,2021-10-06,2024-09-30,DIRECT WINE SHIPPER,NaN,NaN,POINT (-123.032311 45.276215),2,2021-10-06,2021-10-06

In [50]:
## call the top 15 rows
border_data.head (15)

,Serial Number,County,License Type Code,License Class Code,Certificate Number,Premise Name,DBA,Premise Address,Premise Address 2,Premise City,...,Premise Zip,License Issued Date,License Expiration Date,Method of Operation,Days/Hours of Operation,Other,Georeference,Zone,Effective Date,Original Date
0,2000777,ALBANY,HL,242,912771,SUPER HOST HOTELS INC,ALBANY RAMADA PLAZA,3 WATERVLIET AVE,NaN,ALBANY,...,12206,2019-11-15,2021-11-30,HOTEL RESTAURANT SERVING BEER WINE CIDER AND L...,NaN,NaN,POINT (-73.783705 42.674761),2,2019-12-01,1996-12-05
1,1197749,NASSAU,CT,246,913036,MEMORARE CATERERS INC,NaN,2183 JACKSON AVE A,WAVERLY AVE & MERRICK ROAD,SEAFORD,...,11783,2019-11-22,2021-11-30,CATERER SERVING BEER CIDER WINE AND LIQUOR,NaN,NaN,POINT (-73.487062 40.668214),1,2019-12-01,2007-12-18
2,2149537,SULLIVAN,AX,122,910149,AHMED TRADING INC,NaN,1302 STATE ROUTE 52,NaN,LOCH SHELDRAKE,...,12759,2018-11-19,2021-11-30,GROCERY SELLING BEER CIDER AND WINE PRODUCTS,NaN,NaN,POINT (-74.66699 41.777859),2,2018-12-01,2009-12-22
3,1311950,QUEENS,W,322,903719,CAOTICO LLC,FORET WINES,68-38 FOREST AVE,STOREFRONT C,RIDGEWOOD,...,11385,2018-12-31,2021-11-30,WINE STORE SELLING WINE,NaN,NaN,POINT (-73.90109 40.702673),1,2018-12-31,2018-12-31
4,2217319,PUTNAM,TW,344,917985,COFFEE TIME CAFE INC,NaN,559 RTE 6N,NaN,MAHOPAC,...,10541,2019-12-05,2021-11-30,TAVERN SERVING BEER AND WINE,NaN,NaN,POINT (-73.763883 41.374319),2,2019-12-05,2019-12-05
5,1319511,NEW YORK,RW,341,831035,DONATELLA MOXY 7TH AVENUE LLC,PROVA PIZZA BAR,485 7TH AVE,GROUND FLOOR,NEW YORK,...,10123,2019-12-23,2021-11-30,"RESTAURANT SERVING WINE, BEER AND CIDER",NaN,Recorded Music Permitted and No Dancing,NaN,1,2019-12-23,2019-12-23
6,2220767,MONTGOMERY,C,103,935317,CUDA BEVERAGE LLC,BILL'S BEVERAGE,1 WILLOW ST,NaN,AMSTERDAM,...,12010,2020-12-14,2021-11-30,WHOLESALE BEER,NaN,NaN,POINT (-74.1866 42.940987),2,2020-12-14,2020-12-14
7,2129283,ALBANY,WS,308,911084,"SILVERADO VINEYARDS, THE",NaN,6121 SILVERADO TRAIL,NaN,NAPA,...,94558,2018-12-03,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,POINT (-122.33304899999999 38.40974),2,2019-01-01,2005-10-19
8,2138381,ALBANY,WS,308,911310,VOLCANO VINEYARDS LLC,VOLCANO WINERY,35 PILMAUNA DRIVE,NaN,VOLCANO,...,96785,2018-12-10,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,NaN,2,2019-01-01,2007-06-28
9,2160505,ALBANY,WS,308,911278,J J COHN ESTATE LLC,NaN,5055 SOLANO AVE,7079689367,NAPA,...,94558,2018-12-10,2021-12-31,OUT OF STATE DIRECT WINE SHIPPER,NaN,NaN,POINT (-122.33301599999999 38.3548),2,2019-01-01,2010-07-02
10,2175892,ALBANY,WS,308,911215,KENEFICK RANCHES WINERY LLC,KENEFICK RANCH WINERY,4550 SILVERADO TRAIL,NaN,CALISTOGA,...,945159647,2018-12-07,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,POINT (-122.54937700000002 38.57468),2,2019-01-01,2011-08-11
11,2188886,ALBANY,WS,308,909969,KSSM LLC,MICHAEL SCHLUMBERGER,4155 WINE CREEK RD,NaN,HEALDSBURG,...,95448,2018-11-08,2021-12-31,NaN,NaN,NaN,POINT (-122.95010999999998 38.656503),2,2019-01-01,2013-01-10
12,2192454,ALBANY,WS,308,918967,TERRAVANT WINE COMPANY LLC,TERRAVANT WINE COMPANY,35 & 70 INDUSTRIAL WAY,NaN,BUELLTON,...,93427,2019-06-17,2021-12-31,NaN,NaN,NaN,POINT (-120.202402 34.609092),2,2019-06-17,2013-08-30
13,1286881,NEW YORK,OP,252,913420,MERMAID 88 LLC,THE MERMAID INN,570-572 AMSTERDAM AVE,NaN,NEW YORK,...,10024,2019-12-05,2021-12-31,"RESTAURANT SERVING BEER, WINE, CIDER AND LIQUOR",RECORDED MUSIC. NO DANCING.,LICENSED SIDEWALK CAFE.,POINT (-73.97424 40.788753),1,2020-01-01,2015-09-15
14,1289791,BRONX,AX,122,912566,NEW FORDHAM FOOD PLAZA INC,NaN,2487 CRESTON AVE,NaN,BRONX,...,10468,2019-01-10,2021-12-31,GROCERY STORE SELLING BEER CIDER AND WINE PROD...,NaN,NaN,POINT (-73.898153 40.862681),1,2019-01-10,2016-01-28